app/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('post/new/', views.new_post, name='new_post'),
    path('post/tag/new', views.new_tag, name='new_tag'),
    path('post/<slug:slug>/comment/new', views.add_new_comment, name="new_comment"),
    path('<slug:slug>/', views.PostDetail.as_view(), name ='post_detail'),
    path('<slug:slug>/edit', views.PostUpdateView.as_view(), name='edit_post')
]

app/coc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.coc_list, name="coc_list"),
]

app/events/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.eventlist, name='events'),

]

app/sds/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from accounts import views as accounts_views
from home import views as home_views #homepage
from blog import views as blog_views#blog homepage




urlpatterns = [
    path('admin/', admin.site.urls,),
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/update/account', accounts_views.update_profile, name='update_profile'),
    path('profile/update/password', auth_views.PasswordChangeView.as_view(template_name='password_change.html'), name='change_password'),
    path('profile/update/password/done', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    path('reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    path('reset/done',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('reset/complete',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('', home_views.index, name='home'),
    path('blog/', include('blog.urls')),
    path('events/', include('events.urls')),
    re_path(r'^u/(?P<username>[\w\-]+)/$',accounts_views.profile_page,name='profile'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]
urlpatterns += staticfiles_urlpatterns()

app/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
import os

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
    (2, "Withdrawn"),
    (3, "Spam")
)

SLIDERPOS = {
    (0,"First"),
    (1,"Other"),
    (2,"None")
}


class BlogType(models.Model):
    name = models.CharField(max_length=32)
    class Meta:
        verbose_name_plural = "Categories"
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=32)
    def __str__(self):
        return self.name

def user_directory_path(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    timenow = timezone.now()
    return 'cover/{userid}/{date}/{basename}{time}{ext}'.format(userid=instance.author.id, basename=basefilename, date=timenow.strftime("%Y%m%d"), time=timenow.strftime("%H%M%S"), ext=file_extension)

def user_directory_path_slider(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    timenow = timezone.now()
    return 'slider/{userid}/{date}/{basename}{time}{ext}'.format(userid=instance.author.id, basename=basefilename, date=timenow.strftime("%Y%m%d"), time=timenow.strftime("%H%M%S"), ext=file_extension)

class Post(models.Model):
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name='blog_posts')
    blogtype = models.ForeignKey('blog.BlogType', on_delete = models.CASCADE, )
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, help_text='This will define layout of your url eg:studevsoc.com/blog/your-slug')
    tags = models.ManyToManyField(Tag)
    cover = models.ImageField(upload_to=user_directory_path, default='default.png')
    content = RichTextUploadingField()
    updated_on = models.DateTimeField(blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(choices=STATUS, default=0)
    feature = models.BooleanField(default=False, help_text="<b>This will Displayed on Home Page</b>")
    slider = models.BooleanField(default=False, help_text='Add To Blog Slider')
    sliderpos =  models.IntegerField(choices=SLIDERPOS, default=2)
    slidercover = models.ImageField(upload_to=user_directory_path_slider, default='default.png')

    class Meta:
        ordering = ['-updated_on']

    def publish(self):
        self.updated_on = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    def get_page_count(self):
        count = self.posts.count()
        pages = count / 4
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 5

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 4)
        return range(1, count + 1)

    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name="comments")
    author = models. CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    comment_status = models.IntegerField(choices=STATUS, default=1)
    def approve(self):
        self.comment_status = 1
        self.save()
    def __str__(self):
        return self.text

app/events/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
import os

STATUS = (
    (0,"Scheduled"),
    (1,"Draft"),
    (2,"Withdrawn")
)

def user_directory_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    timenow = timezone.now()
    return 'events/{userid}/{date}{basename}{time}{ext}'.format(userid=instance.scheduler.id, basename=basefilename, date=timenow.strftime("%Y%m%d"), time=timenow.strftime("%H%M%S"), ext=file_extension)

class EventCategory(models.Model):
    name = models.CharField(max_length=32, unique=True)
    class Meta:
        verbose_name_plural = "Categories"
    def __str__(self):
        return self.name

class Event(models.Model):
    scheduler = models.ForeignKey(User, on_delete= models.CASCADE, related_name="events")
    eventtype = models.ForeignKey('events.EventCategory', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date = models.DateTimeField(blank=True, null=True)
    enddate = models.DateTimeField(blank=True, null=True)
    venue = models.CharField(max_length=200)
    maplink = models.URLField(max_length=200, blank=True, default="#")
    cover = models.ImageField(upload_to=user_directory_path, default='defaultevent.jpg')
    about = RichTextUploadingField()
    scheduled_on = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(choices=STATUS, default=1)
    slug = models.SlugField(max_length=200, unique=True, help_text='WARNING : Use the same slug for while creating a BLOG Post about events')
    website = models.URLField(max_length=200, blank=True, default="#")
    registration = models.URLField(max_length=200, blank=True, default="#")

    class Meta:
        ordering = ['-date']

    def publish(self):
        self.scheduled_on = timezone.now()
        self.save()

    def __str__(self):
        return self.name

app/blog/forms.py
from django import forms
from .models import Post, Comment, Tag, BlogType
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())
    cover = forms.ImageField(label='Select an Image')
    class Meta:
        model = Post
        fields = ('title', 'cover', 'content', 'slug', 'tags', 'blogtype')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class TagForm(forms.ModelForm):
    name = forms.CharField(max_length=32, label='Tag Name ')
    class Meta:
        model = Tag
        fields = ('name',)

class BlogTypeForm(forms.ModelForm):

    class Meta:
        model = BlogType
        fields = ('name',)

app/events/forms.py
from django import forms
from .models import Event, EventCategory
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class EventForm(forms.ModelForm):
    about = forms.CharField(widget=CKEditorUploadingWidget())
    cover = forms.ImageField(label='Select an Image')
    class Meta:
        model = Event
        fields = ('name', 'cover', 'about','date', 'enddate', 'venue', 'slug', 'website', 'registration', 'eventtype',)

class EventCategoryForm(forms.ModelForm):
    class Meta:
        model = EventCategory
        fields = ('name',)

app/home/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Contact
        fields = ('name','email','subject','message')

app/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator


from .models import Post
from .forms import PostForm, CommentForm, TagForm, BlogTypeForm

#Post List View
class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-updated_on')
    template_name = 'blog.html'
    paginate_by = 4

class PostListPub(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-updated_on')
    template_name = 'new_tag.html'
    paginate_by = 4

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'
    def get_context_data(self, **kwargs):
        context = super(PostDetail , self).get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(status=1).order_by('-updated_on')
        return context

@method_decorator(login_required, name='dispatch')
class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ('content','tags',)
    template_name = 'edit_post.html'
    SlugField = 'slug'
    context_object_name = 'post'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_on = timezone.now()
        post.status = 0
        post.save()
        return redirect('post_detail', slug=post.slug )


@login_required
def new_tag(request):
    posts = Post.objects.filter(status=1).order_by('-updated_on')
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.save()
            return redirect('new_post')
    else:
        form = TagForm()
    return render(request, 'new_tag.html', {'form':form,'posts': posts})


#new post view
@login_required
def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created_date = timezone.now()
            post.status = 0
            post.save()
            return redirect('post_detail',slug=post.slug)
    else:
        form = PostForm()
    return render(request, 'new_post.html', {'form':form})

#new_tag view


#new categories
@login_required
def new_blogtype(request):
    if request.method == 'POST':
        form = BlogTypeForm(request.POST)
        if form.is_valid():
            blogtype = form.save(commit=False)
            blogtype.save()
            return redirect('new_post')
    else:
        form = BlogTypeForm
    return render(request, 'new_tag.html', {'form':form})

#add comment
@login_required
def add_new_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('post_detail', slug=post.slug)
    else:
        form = CommentForm()
    return render(request, 'comment.html', {'form':form})

app/events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from datetime import date, datetime


from .models import Event
from .forms import EventForm, EventCategoryForm

def eventlist(request):
    today = date.today()
    current = datetime.today()
    upcomings = Event.objects.filter(date__gt=current, status=0).order_by('-date')
    pasts = Event.objects.filter(date__lt=today, status=0).order_by('-date')
    ongoing = Event.objects.filter(date__year=today.year, date__month=today.month, date__day=today.day, status=0).order_by('-date')
    return render(request, 'events.html', {'upcomings':upcomings, 'pasts':pasts, 'ongoing':ongoing})

app/home/views.py
from django.shortcuts import render, redirect
from django.views import generic
from blog.models import Post
from .models import Jumbotron, Project, Contact
from blog.models import Post
from django.utils import timezone
from .forms import ContactForm
from django.contrib import messages
# Home Page for SDS
def homeviews(request):
    posts = Jumbotron.objects.filter(status=1).order_by('-updated_on')
    features = Post.objects.filter(feature=1, status=1).order_by('-updated_on')
    projects = Project.objects.filter().order_by('-updated_on')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            connect = form.save(commit=False)
            connect.sds_response = 0
            connect.date = timezone.now()
            connect.save()
            messages.success(request, 'Submited successfully')
            return redirect('home')
        else:
            messages.error(request,'Invalid Data<br>Please Input valid data , Check all the fields one more time')
    else:
        form = ContactForm()
    context = {'posts': posts,'features':features,'projects':projects,'form':form}
    return render(request, 'home.html', context)
def index(request):
    return render(request,'sdshome/index.html')

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="Student Developers Society is a community aiming to bridge the gap between students and professionals and make the students industry ready">
  <meta name="author" content="Student Developers Society">
  <meta name="keywords" content="SDS, StuDevSoc, Student Developers Society, SDS Cochin, StuDevSoc Kochi, Student Developers Society Kochi, SDS community, StuDevSoc Team, Student Developers" />
  <title>{% block title %}Student Developers Society{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type='image/x-icon'>
  <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  {% block stylesheet %}{% endblock %}
</head>

<body>
  {% block body %}

  <nav class="navbar sticky-top navbar-expand-lg navbar-light  bg-white">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static 'img/logo.png' %}" width="100" height="30" alt="">
    </a>
    <!--  <div class="typewriter">
    <h5 class=>Welcome to SDS</h5>
    </div>-->




    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
          <a class="nav-link" href="{% url 'home' %}">Home
            {% if request.resolver_match.url_name == 'home' %}
            <span class="sr-only">(current)</span>
            {% endif %} </a>

        </li>
        <li class="nav-item  {% if request.resolver_match.url_name == 'blog' %}active{% endif %}">
          <a class="nav-link" href="{% url 'blog' %}">Blog</a></li>
        <li class="nav-item {% if request.resolver_match.url_name == 'events' %}active{% endif %}">
          <a class="nav-link" href="{% url 'events' %}">Events</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SDS Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% if user.is_authenticated %}

            <a class="dropdown-item disabled" href="#">Welcome {{ user.username }}</a>
            {% if user.is_staff %}
            <a class="dropdown-item" href="{% url 'admin:index' %}">Administration</a>
            {% endif %}

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'new_post' %}">Write a post</a>
            <a class="dropdown-item" href="{% url 'profile' request.user %}">My Profile</a>
            <a class="dropdown-item" href="{% url 'update_profile' %}">Edit Account</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            {% else %}

            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            <a class="dropdown-item" href="{% url 'signup' %}">Sign up</a>
            {% endif %}
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Code of Conduct</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Get in touch</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block breadcrumb %}
    {% endblock %}


  </div>
  {% block content %}
  {% endblock %}
  {% endblock body %}

  <!--Footer-->
  <footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn ">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="#" target="_blank" role="button">Reach Us
        <i class="fas fa-envelope ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="#" target="_blank" role="button">Join Us
        <i class="fas fa-users ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/StuDevSoc" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/thisissds" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/channel/UC70uGj" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://www.linkedin.com/company/studevsoc/" target="_blank">
        <i class="fab fa-linkedin mr-3"></i>
      </a>

      <a href="https://t.me/studevsoc" target="_blank">
        <i class="fab fa-telegram mr-3"></i>
      </a>

      <a href="https://www.instagram.com/studevsoc/" target="_blank">
        <i class="fab fa-instagram mr-3"></i>
      </a>

      <a href="https://gitlab.com/studevsoc" target="_blank">
        <i class="fab fa-gitlab mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      SDS 2019
      <a href="#" target="_blank">SDS</a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->
  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  {% block js %}
  {% endblock %}


</body>

</html>

app/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">SDS Accounts</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post a reply</button>
  </form>
</div>

{% endblock %}

app/templates/events2.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="mt-5">
  <div class="container">
    <section class="text-center">
      {% if upcomings.all %}
      <h2 class="h1-responsive font-weight-bold text-center my-5">Upcoming Events</h2>
      <!-- Section description -->
      <p class="text-center w-responsive mx-auto mb-5">Recent Posts which are submitted and under review or published</p>

      <div class="row mb-4 wow fadeIn">
        {% for event in upcomings %}
        {% include 'includes/event_list.html' %}
        <a href="{{ event.registration }}" target="_blank" class="btn btn-primary btn-md">Registration
          <i class="fas fa-mouse-pointer ml-2"></i>
        </a>
      </div>

  </div>

  <!--/.Card-->

  </div>
  {% endfor %}
  </div>
  {% endif %}

  {% if ongoing.all %}
  <h2 class="h1-responsive font-weight-bold text-center my-5">Ongoing Events</h2>
  <!-- Section description -->
  <p class="text-center w-responsive mx-auto mb-5">Recent Posts which are submitted and under review or published</p>
  <!--Grid row-->
  <div class="row mb-4 wow fadeIn">
    {% for event in ongoing %}
    {% include 'includes/event_list.html' %}
    <a href="#" target="_blank" class="btn btn-primary btn-md disabled">Registration
      <i class="fas fa-mouse-pointer ml-2"></i>
    </a>
  </div>

</div>

<!--/.Card-->

</div>
    {% endfor %}
  </div>
  {% endif %}
  <!--Pagination-->
  {% if pasts.all %}
  <h2 class="h1-responsive font-weight-bold text-center my-5">Past Events</h2>
  <!-- Section description -->
  <p class="text-center w-responsive mx-auto mb-5">Recent Posts which are submitted and under review or published</p>
  <!--Grid row-->
  <div class="row mb-4 wow fadeIn">
    {% for event in pasts %}
    {% include 'includes/event_list.html' %}
    <a href="{% url 'post_detail' event.slug %}" target="_blank" class="btn btn-primary btn-md">Read Blog
      <i class="fas fa-file ml-2"></i>
    </a>
  </div>

</div>

<!--/.Card-->

</div>
    {% endfor %}
  </div>
  {% endif %}


  </section>
  </div>
</main>
{% endblock %}

app/templates/new_post.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Create a Post {% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}



{% block content %}
{% include 'includes/post_notification.html' %}
<div class="container">
  <form method="post" class="mb-4" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Submit</button>
  </form>
</div>

{% endblock %}

app/templates/password_change.html
{% extends 'base_accounts.html' %}

{% block title %}Change Password{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-8 col-md-10 col-sm-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Update Your SDS Profile Password</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <button type="submit" class="btn btn-primary btn-block">Update Password</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}